import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Typography from "@mui/material/Typography";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>MQTT app</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Link href="/mqtt">
                    <Typography variant="h2" component="h1">
                        To MQTT Page
                    </Typography>
                </Link>
            </main>
        </div>
    );
}
